### ISSUE TITLE
Logo?

### ISSUE THREAD

**Issue by ryanpcmcquen** [SurLaTable/slt-ui#12]
Low priority, but it would be nice to have a logo on the README:
![slt-ui__logo](https://user-images.githubusercontent.com/772937/42175152-6f172306-7dd9-11e8-8ff0-e60374dcf8d5.png)

**Comment by ryanpcmcquen** [comment]
Hey @richardbmx, thank you so much for reaching out! We are currently evaluating a name change for this project, so hold tight. :unicorn:

**Comment by richardbmx** [comment]
perfect when you want a logo with pleasure I can do it

**Comment by ryanpcmcquen** [comment]
@richardbmx, the new name of the organization is going to be `georgetown-labs`, if you want to design a logo.

**Comment by richardbmx** [comment]
@ryanpcmcquen  Perfect I will work on it

**Comment by richardbmx** [comment]
@ryanpcmcquen  can you explain what the project is about so that you can have an idea and ensure that the logo is related to the functions of the project

**Comment by ryanpcmcquen** [comment]
@richardbmx, thank you. The focus for the project is to allow modern React components to work on legacy systems.

**Comment by ryanpcmcquen** [comment]
@richardbmx, we don't know the name of the project yet, only the organization. It may split into multiple repos, but they would all share the Georgetown Labs logo.

**Comment by richardbmx** [comment]
@ryanpcmcquen  I present this proposal based on performing the G in a modern and minimalist way that at first glance is easy to recognize to give identity to your organization

![logo105](https://user-images.githubusercontent.com/35604837/46042784-363f6180-c0e4-11e8-9290-8419c3ae0cd1.png)

**Comment by richardbmx** [comment]
@ryanpcmcquen  I present this second model that also fits very well in different presentations

![logo1052](https://user-images.githubusercontent.com/35604837/46050911-b1b10b00-c104-11e8-948b-cc328ed2fd77.png)

**Comment by richardbmx** [comment]
@ryanpcmcquen  you indicate me the one you like to create a google folder with all the necessary files to use the logo

**Comment by ryanpcmcquen** [comment]
Wow, @richardbmx, I am impressed!!! Let me discuss this with the team. Thank you again!

**Comment by ryanpcmcquen** [comment]
@richardbmx, I am really sorry, we are close to code freeze and on a tight deadline, we will get back to you as soon as possible.

**Comment by ryanpcmcquen** [comment]
@LeonardMeagher2, unless you have an objection, I would like to go with the first logo.

**Comment by ryanpcmcquen** [comment]
@richardbmx, let’s go with the first!

**Comment by richardbmx** [comment]
@ryanpcmcquen  perfect I will make the folder with all the files and if you want I can make an extration request to add the logo

**Comment by richardbmx** [comment]
@ryanpcmcquen  Here I give you the link with all the necessary files to use the logo, inside you find different variations of the logo to be used in different applications as well as the original files to edit them if you need it. Any questions you can write me I am ready for next projects if you wish.

[Google Drive](https://drive.google.com/open?id=1qkvd0-r9g-0bufYsU99pQrDGcT51ESNh)

**Comment by ryanpcmcquen** [comment]
@richardbmx, you are a gentleman and a scholar. Thank you!

**Comment by richardbmx** [comment]
Thank you for allowing me to contribute to your project

**Comment by richardbmx** [comment]
I would like to see the logo in use ;-)

**Comment by ryanpcmcquen** [comment]
Me too. Putting it here for now!
https://github.com/SurLaTable/georgetown-labs-branding
