### ISSUE TITLE
Find a pattern for providing data to components.

### ISSUE THREAD

**Issue by ryanpcmcquen** [SurLaTable/slt-ui#52]
We already have a `services` directory, that provides a proxy for various api services, but we should also find a way to provide that data to components without coupling them to specific services.

One scenario that could be considered, the `LocationField` component grabs data from a _Google Maps_ API, but another user may want to use _Open Street Map_'s API. Another user still may already have the data and just want to pass it down to the component. If we can keep the component pure and pass this data through some type of provider it allows us to keep the greatest level of modularity and flexibility. It also allows others using this library to tailor it to their needs.

Something to consider is that the component will expect a certain type of model of the data. Where does this data get transformed and normalized. Do we document the data model as part of the component?

Feel free to drop some of your great ideas on this enhancement here @LeonardMeagher2 & @terryfritsch.

**Comment by LeonardMeagher2** [comment]
I believe this is solved, so I'm going to close it, but it can always be brought back up.

**Comment by ryanpcmcquen** [comment]
Thanks to https://github.com/LeonardMeagher2/redux-reheat!
